Blog/Controllers/ArticulosController.cs
using Blog.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.Controllers
{
    public class ArticulosController : Controller
    {
        [HttpPost]
        public ActionResult GuardarArticulo(string titulo, string imagen, 
            string texto, HttpPostedFileBase imagenFile)
        {
            Articulo nuevoArticulo = new Articulo();
            nuevoArticulo.Titulo = titulo;
            nuevoArticulo.Imagen = imagen;
            nuevoArticulo.Texto = texto;
            nuevoArticulo.Autor = (Usuario)Session["UsuarioLogueado"];

            ArticulosManager manager = new ArticulosManager();
            nuevoArticulo = manager.Insertar(nuevoArticulo);

            if(imagenFile != null)
            {
                imagenFile.SaveAs(Server.MapPath("~/Content/images/articulos/" + nuevoArticulo.ID + ".png"));
            }

            return RedirectToAction("Index", "Home");

            ////List<Articulo> listaArticulos = (List<Articulo>)Session["Articulos"];
            ////if(listaArticulos == null) 
            ////{
            ////    //es el primer artículo
            ////    listaArticulos = new List<Articulo>();
            ////}
            ////listaArticulos.Add(nuevoArticulo);
            ////Session["Articulos"] = listaArticulos;
        }

        public ActionResult Ver(long ID)
        {
            ArticulosManager manager = new ArticulosManager();
            Articulo articulo = manager.Consultar(ID);
            ViewBag.Articulo = articulo;
            return View();
        }
    }
}

Blog/Controllers/HomeController.cs
using Blog.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace Blog.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            //List<Articulo> articulos = (List<Articulo>)Session["Articulos"];

            ArticulosManager manager = new ArticulosManager();
            List<Articulo> articulos = manager.ConsultarTodos();
            ViewBag.Articulos = articulos;
            return View();
        }    

        public ActionResult Contacto()
        {
            return View();                
        }

        [HttpPost]
        public ActionResult MailContacto(string nombre, string mail, string mensaje)
        {
            //Definimos la conexión al servidor SMTP que vamos a usar
            //para mandar el mail. Hay que buscarla en nuestro proveedor
            SmtpClient clienteSmtp = new SmtpClient("smtp.gmail.com", 587);
            clienteSmtp.Credentials = new NetworkCredential("testcomunidadit@gmail.com", "testcomit2017");
            clienteSmtp.EnableSsl = true;

            //Generamos el objeto MAIL a enviar
            MailMessage mailAEnviar = new MailMessage();
            mailAEnviar.From = new MailAddress("testcomunidadit@gmail.com", "Test ComunidadIT");
            mailAEnviar.To.Add("testcomunidadit@gmail.com");
            mailAEnviar.Subject = "Te contactaron del blog!";
            mailAEnviar.Body = nombre + "(" + mail + ") te dejó un contacto en el blog. Su mensaje fue: " + mensaje;            

            //mandamos el mail
            clienteSmtp.Send(mailAEnviar);

            //vamos a mandarle un mail al usuario que nos dejó el contacto
            MailMessage mailAUsuario = new MailMessage();
            mailAUsuario.From = new MailAddress("testcomunidadit@gmail.com", "Test ComunidadIT");
            mailAUsuario.To.Add(mail);
            mailAUsuario.Subject = "Gracias por contactarte con nosotros!";
            mailAUsuario.IsBodyHtml = true;
            mailAUsuario.Body = "Hola " + nombre + ", <br>Gracias por contactarte con nosotros!<br>Te responderemos a la brevedad.<br>Nos dejaste los siguientes datos:<br>Mail: " + mail + "<br>Mensaje: " +mensaje+ "<br><br>Saludos!!!<br><b>Velez Blog</b><img src=\"http://www.losandes.com.ar/files/image/16/02/image56c3c893e34058.75676825.jpg\" />";

            clienteSmtp.Send(mailAUsuario);

            return View("Contacto");
        }
    }
}

Blog/Views/Home/Contacto.cshtml
@{
    ViewBag.Title = "Contacto";
}

@section styles{    
    <link href="~/Content/contacto.css" rel="stylesheet" />
}


<h2>Contacto</h2>

<p>Esta es la página de contacto del Blog de Vélez.</p>
<p>Por favor, ante cualquier duda o comentario, dejanos tu mensaje:</p>

<form action="@Url.Action("MailContacto", "Home")" method="post">
    <div class="col-md-6">
        <div class="form-group">
            <label for="nombre">Nombre</label>
            <input type="text" class="form-control" id="nombre" name="nombre" required>
        </div>
        <div class="form-group">
            <label for="mail">Mail</label>
            <input type="email" class="form-control" id="mail" name="mail" required>
        </div>
        <div class="form-group">
            <label for="mensaje">Mensaje</label>
            <textarea id="mensaje" class="form-control"  name="mensaje" required></textarea>
        </div>
        <input type="submit" value="Enviar" />
    </div>
</form>

Blog/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="http://www.losandes.com.ar/files/image/16/02/image56c3c893e34058.75676825.jpg" alt="Mariano Pavone">
            <div class="carousel-caption">
                <h3>Pavone Jugador del año</h3>
                <p>Lo eligieron..</p>
            </div>
        </div>
        <div class="item">
            <img src="http://cdn4.uvnimg.com/dims4/default/6066e85/2147483647/thumbnail/1240x698/quality/75/?url=http%3A%2F%2Fcdn2.uvnimg.com%2F2e%2F18%2Fa1dfb79d4816b9999af32a2efbc6%2FMarti%25CC%2581nez.jpg" alt="...">
            <div class="carousel-caption">
                <h3>El burrito puede llegar a volver</h3>
                <p>Los hinchas están entusiasmados</p>
            </div>
        </div>
        <div class="item">
            <img src="~/Content/images/asad.jpg"  alt="Asad"/>
            <div class="carousel-caption">
                <h3>El turquito Asad se fue a USA</h3>
                <p>Se lo llevó el Tata</p>
            </div>
        </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<!-- SECCIONES IMPORTANTES -->
<div class="text-center col-md-4 col-md-offset-0 col-xs-10 col-xs-offset-1">
    <img class="img-circle" src="~/Content/images/jugadores.jpg" alt="jugadores" width="140" height="140">
    <h3>Jugadores</h3>
    <p>Acá verás la información del plantel del equipo</p>
    <button class="btn btn-default">Ver mas...</button>
</div>

<div class="text-center col-md-4 col-md-offset-0 col-xs-10 col-xs-offset-1">
    <img class="img-circle" src="~/Content/images/fixture.jpg" alt="fixture" width="140" height="140">
    <h3>Partidos</h3>
    <p>Los próximos partidos y fixture completo</p>
    <button class="btn btn-default" data-toggle="modal" data-target="#modalFixture">Ver mas...</button>
</div>
<div class="text-center col-md-4 col-md-offset-0 col-xs-10 col-xs-offset-1">
    <img class="img-circle" src="~/Content/images/amalfitani.jpg" alt="amalfitani" width="140" height="140">
    <h3>El Club</h3>
    <p>Información del club para socios y simpatizantes.....</p>
    <button class="btn btn-default">Ver mas...</button>
</div>

<!-- Artículos -->
<h2>Artículos</h2>
<div id="articulos">    
    @if (ViewBag.Articulos != null)
    {
        foreach (Blog.Models.Articulo articulo in ViewBag.Articulos)
        {
            <div class="col-md-6">
                <a href="@Url.Action("Ver", "Articulos", new { ID = articulo.ID })">
                    @if (string.IsNullOrEmpty(@articulo.Imagen))
                    {
                        <img class="img-responsive" src="~/Content/images/articulos/@(articulo.ID).png" alt="imagen">
                    }
                    else
                    {
                        <img class="img-responsive" src="@articulo.Imagen" alt="imagen">
                    }
                    <h3>@articulo.Titulo</h3>
                    <p>@articulo.Texto</p>
                </a>
            </div>
        }
    }
</div>

<!-- Modal Fixture -->
<div class="modal fade" id="modalFixture" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Fixture</h4>
            </div>
            <div class="modal-body">
                Todavía no se sabe si se va a jugar el campeonato.
                <!--<img class="img-responsive" src="images/fixture.jpg" alt="fixture">-->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>


<!-- Modal Nuevo Artículo -->
<div class="modal fade" id="modalArticulo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="@Url.Action("GuardarArticulo","Articulos")" method="post" enctype="multipart/form-data">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Nuevo artículo</h4>
                </div>
                <div class="modal-body">
                    @*<div class="form-group">
                        <label for="idArticulo">ID</label>
                        <input type="number" min="1" id="idArticulo" name="id">
                    </div>*@
                    <div class="form-group">
                        <label for="tituloArticulo">Título</label>
                        <input type="text" id="tituloArticulo" name="titulo">
                    </div>
                    <div class="form-group">
                        <label for="imagenArticulo">Imagen</label>
                        <!--<input type="file" id="imagenArticulo">-->
                        <input type="text" id="imagenArticulo" name="imagen">
                    </div>
                    <div class="form-group">
                        <label for="imagenArticuloInput">Imagen</label>
                        <input type="file" id="imagenArticuloInput" name="imagenFile">                        
                    </div>
                    <div class="form-group">
                        <label for="textoArticulo">Texto</label>
                        <textarea type="text" id="textoArticulo" name="texto"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <input id="guardarArticulo" type="submit" class="btn btn-primary" value="Guardar">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </form>
        </div>
    </div>
</div>